#!/usr/bin/env bash
set -euo pipefail

BUNDLE="${1:-}"
if [ -z "$BUNDLE" ]; then echo "Usage: $0 <sgfp_bundle_dir>"; exit 1; fi
REPORT="$BUNDLE/report.md"

POD_DIR=$(find "$BUNDLE" -maxdepth 1 -type d -name 'pod_*' | head -n1 || true)
NODE_DIR=$(find "$BUNDLE" -maxdepth 1 -type d -name 'node_*' | head -n1 || true)
AWS_DIR=$(find "$BUNDLE" -maxdepth 1 -type d -name 'aws_*' | head -n1 || true)

POD=$(basename "$BUNDLE" | sed 's/^sgfp_bundle_\(.*\)_[0-9].*/\1/')
NODE="$(basename "${NODE_DIR:-}" | sed 's/^node_//')"

POD_ANNO="$POD_DIR/pod_annotations.json"
POD_COND="$POD_DIR/pod_conditions.json"
POD_NET="$POD_DIR/pod_netns_routes_rules.txt"
POD_SGS="$POD_DIR/pod_branch_eni_sgs.txt"
REACH="$POD_DIR/pod_reachability.txt"
AWS_NODE_LOG_POD="$POD_DIR/aws_node_full.log"
CONN="$NODE_DIR/node_conntrack_mtu.txt"
TRUNK_JSON="$AWS_DIR/trunk_eni.json"
BR_JSON="$AWS_DIR/_all_branch_enis_in_vpc.json"

say(){ echo "- $1" >> "$REPORT"; }

echo "# SGFP Network Diagnostics Report" > "$REPORT"
echo "Pod: \`$POD\`" >> "$REPORT"
[ -n "$NODE" ] && echo "Node: \`$NODE\`" >> "$REPORT"
echo "Generated: \`$(date)\`" >> "$REPORT"
echo >> "$REPORT"

echo "## ✅ Pod Networking" >> "$REPORT"

if [ -s "$POD_ANNO" ] && jq -er '."vpc.amazonaws.com/pod-eni"' "$POD_ANNO" >/dev/null 2>&1; then
  say "**Pod ENI assigned** ✅ (SG-for-Pods)"
else
  say "**No Pod ENI annotation** ❌ (mutation may have failed)"
fi

if [ -s "$POD_NET" ] && grep -Eq 'table (100|101)' "$POD_NET"; then
  say "**Per-pod routing table exists** ✅"
else
  say "**Missing per-pod routing table** ❌"
fi

if [ -s "$POD_SGS" ]; then
  echo >> "$REPORT"
  echo "### 🔒 Pod ENI Security Groups" >> "$REPORT"
  sed 's/^/- `&`/' "$POD_SGS" >> "$REPORT"
fi

if [ -s "$REACH" ]; then
  if grep -qi "100% packet loss" "$REACH"; then
    say "ICMP reachability failed (often blocked) ⚠️"
  else
    say "ICMP reachability OK ✅"
  fi
fi

if [ -s "$AWS_NODE_LOG_POD" ]; then
  if grep -Eiq 'rate.?exceeded|throttl|attach|branch|trunk|fail|error' "$AWS_NODE_LOG_POD"; then
    say "Interesting CNI events in pod aws-node logs ⚠️  (see \`pod_*/aws_node_full.log\`)"
  else
    say "aws-node logs (pod scope) look clean ✅"
  fi
fi

echo >> "$REPORT"
echo "## 🧠 Node State" >> "$REPORT"

if [ -s "$CONN" ]; then
  pair="$(grep -Eo '[0-9]+\s*/\s*[0-9]+' "$CONN" | head -n1 || true)"
  if [ -n "$pair" ]; then
    CT="$(printf '%s' "$pair" | awk -F'/' '{gsub(/ /,"",$1); print $1}')"
    MX="$(printf '%s' "$pair" | awk -F'/' '{gsub(/ /,"",$2); print $2}')"
    if printf '%s' "$CT" | grep -Eq '^[0-9]+$' && printf '%s' "$MX" | grep -Eq '^[0-9]+$' && [ "$MX" -gt 0 ]; then
      PCT="$(awk -v c="$CT" -v m="$MX" 'BEGIN{printf "%d%%", (100*c)/m}')"
      say "Conntrack usage: **$CT / $MX (~$PCT)**"
    fi
  fi
  if grep -Eiq 'nf_conntrack|fragmentation needed|blackhole' "$CONN"; then
    say "Kernel shows conntrack/fragmentation/blackhole hints ⚠️"
  fi
else
  say "Conntrack/MTU capture missing ⚠️"
fi

echo >> "$REPORT"
echo "## 🌩️ AWS ENI State" >> "$REPORT"

if [ -s "$TRUNK_JSON" ] && jq -e '.NetworkInterfaces or .[0]?' "$TRUNK_JSON" >/dev/null 2>&1; then
  say "Trunk ENI present ✅"
else
  say "Trunk ENI not found ❌"
fi

if [ -s "$BR_JSON" ] && jq -e 'length>0' "$BR_JSON" >/dev/null 2>&1; then
  say "Branch ENIs present (in VPC scan) ✅"
else
  say "No branch ENIs found in VPC scan (or insufficient perms) ⚠️"
fi

echo >> "$REPORT"
echo "---" >> "$REPORT"
echo "_Report generated by sgfp_report.sh_" >> "$REPORT"

echo "✅ Report written to: $REPORT"
